name: CI Builds
on: [push, pull_request]

jobs:
    build:
        name: Build and Test
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - id: install
              run: npm install
            - id: build
              run: npm run compile
            - id: test
              run: npm test
