name: CI Builds
on: [push, pull_request]

jobs:
    build:
        name: Build and Test
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [windows-latest, macOS-latest]
                # os: [ubuntu-latest, windows-latest, macOS-latest]
            fail-fast: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - id: install
              run: npm install
            - id: build
              run: npm run compile
            - id: test
              run: npm run testOnly
            - id: integtest
              run: npm run integrationTestOnly
